name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert matplotlib numpy pandas pyyaml

      - name: Set up Lean (elan)
        uses: leanprover/elan-action@v1

      - name: Lake build
        run: |
          lake build | cat || true

      - name: Run checks
        run: |
          make check | cat || true

      - name: Build all
        run: |
          make all | cat || true
