name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert matplotlib numpy pandas pyyaml

      # === Install elan (Lean toolchain) ===
      - name: Install elan
        shell: bash
        run: |
          curl -sSfL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh \
            | bash -s -- -y --default-toolchain $(cat lean-toolchain)
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
          echo "Elan installed at $HOME/.elan/bin"

      - name: Lean/Lake versions
        run: |
          lean --version
          lake --version

      - name: Lake build
        run: |
          lake update
          lake build

      - name: make check
        run: make check

      - name: make all
        run: make all
